export const flowSystem = {
  appState: {
    viewBackgroundColor: "transparent",
    theme: "light",
    language: "zh-CN",
  },
  elements: [
    // 从左到右依次排列的四个主要节点
    {
      id: "happiness",
      type: "rectangle",
      x: 100,
      y: 200,
      width: 140,
      height: 60,
      backgroundColor: "#FFB6C1",
      strokeColor: "#FF69B4",
      fillStyle: "solid",
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: "happiness-text",
      type: "text",
      x: 120,
      y: 220,
      width: 100,
      height: 25,
      text: "为什么不快乐",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "happiness",
    },
    {
      id: "consciousness",
      type: "rectangle",
      x: 320,
      y: 200,
      width: 140,
      height: 60,
      backgroundColor: "#B0E0E6",
      strokeColor: "#4682B4",
      fillStyle: "solid",
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: "consciousness-text",
      type: "text",
      x: 340,
      y: 220,
      width: 100,
      height: 25,
      text: "意识控制",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "consciousness",
    },
    {
      id: "elements",
      type: "rectangle",
      x: 540,
      y: 200,
      width: 140,
      height: 60,
      backgroundColor: "#98FB98",
      strokeColor: "#228B22",
      fillStyle: "solid",
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: "elements-text",
      type: "text",
      x: 560,
      y: 220,
      width: 100,
      height: 25,
      text: "心流要素",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "elements",
    },
    {
      id: "goals",
      type: "rectangle",
      x: 760,
      y: 200,
      width: 140,
      height: 60,
      backgroundColor: "#F0E68C",
      strokeColor: "#DAA520",
      fillStyle: "solid",
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: "goals-text",
      type: "text",
      x: 780,
      y: 220,
      width: 100,
      height: 25,
      text: "目标设定",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "goals",
    },
    // 连接箭头
    {
      id: "arrow1",
      type: "arrow",
      x: 240,
      y: 230,
      points: [
        [0, 0],
        [80, 0],
      ],
      strokeColor: "#666",
      strokeWidth: 2,
    },
    {
      id: "arrow2",
      type: "arrow",
      x: 460,
      y: 230,
      points: [
        [0, 0],
        [80, 0],
      ],
      strokeColor: "#666",
      strokeWidth: 2,
    },
    {
      id: "arrow3",
      type: "arrow",
      x: 680,
      y: 230,
      points: [
        [0, 0],
        [80, 0],
      ],
      strokeColor: "#666",
      strokeWidth: 2,
    },
    // 每个节点下方的要点说明
    {
      id: "happiness-points",
      type: "text",
      x: 70,
      y: 280,
      width: 200,
      height: 80,
      text: "• 宇宙不以人类为中心\n• 快乐源于心灵阐释\n• 控制意识才能控制体验",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    {
      id: "consciousness-points",
      type: "text",
      x: 290,
      y: 280,
      width: 200,
      height: 80,
      text: "• 意识是可感知可引导的\n• 注意力决定意识内容\n• 资讯中性，阐释决定好坏",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    {
      id: "elements-points",
      type: "text",
      x: 510,
      y: 280,
      width: 200,
      height: 80,
      text: "• 全神贯注+自我进步\n• 明确目标、适度挑战\n• 即时反馈、沉浸感",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    {
      id: "goals-points",
      type: "text",
      x: 730,
      y: 280,
      width: 200,
      height: 80,
      text: "• 精简目标减少冲突\n• 找到真正重要的事\n• 平衡挑战与能力",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    // 箭头上方的过程说明
    {
      id: "process1",
      type: "text",
      x: 240,
      y: 180,
      width: 80,
      height: 30,
      text: "理解本质",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
    },
    {
      id: "process2",
      type: "text",
      x: 460,
      y: 180,
      width: 80,
      height: 30,
      text: "掌控意识",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
    },
    {
      id: "process3",
      type: "text",
      x: 680,
      y: 180,
      width: 80,
      height: 30,
      text: "设定目标",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
    }
  ],
  UIOptions: {
    canvasActions: {
      loadScene: false,
      saveAsImage: true,
      saveToActiveFile: false,
      export: false,
      toggleTheme: false,
    },
    defaultSidebarDockedPreference: true,
  }
}; 